from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon.png'

# Colors
PRIMARY_COLOR = "#1e8eb0"
DARKER_PRIMARY_COLOR = "#16488a"
DARKEST_PRIMARY_COLOR = "#0E3A5E"

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500